hostname: k3os-master-1
ssh_authorized_keys:
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwQE+i/TF9esDWjZPwIU5CE4AVfkP2XahZZnYLJLbfHnk69SoMambtp4pS5EqQ50tKE86X5y18NhFYAkIU2bWIxsy8lD6e/pEb93f7WA7V92iqVtrqQpQyf36UgQc9v4KJjNDgnvnLk9qiaFGbxxokNzI9er+0nSiGDtN1iNLUQmFwe07RO533437pVypJFBhPwxvgN76jiSGYedDc64gJQcjGAH1Qxlh7N8Xqg417w1ov7vf+EE5uf/MOI5jt5qxw215wP5qscPC4OHyW2Jt9G+i5dIb5mlfEEjL+NzgBBV/3swaYJVS8pfrpxeN3TJeMt72ODhT/DzLwvjuErHe9DrrjA5yXhr+LkhwOYGB20XswtjSqnwp0lRU29ZtlBpk23G0cJkRhKkFfQ1lzQD+RQkNSruNgxbjB+F0xiPAbps80LSK3D7nOwAF84dMBkUJAfND8RH9wZGayYeBMxvhato+mRIXG180luY25v/LxvZZ/arm/IlYNuPCNMVG+gEM="
# rob@pop-os



